#' Builds a \code{data.frame} containing publication info from an \code{RISmed}
#' query
#'
#' This function takes the output of \code{RISmed::EUtilsGet} and builds a
#' \code{data.frame} containing information related to each publication from the
#' query including title, abstract, year of publication, author, journal
#' information. It may only be applied to objects of class
#' \code{Medline}.
#'
#' @param x An object of class \code{RISmed::Medline} generated by
#' \code{RISmed::EUtilsGet}
#'
#' @return A \code{data.frame} containing information for each publicaiton from
#' the \code{RISmed} query
#'
#' @export
#'
#' @seealso \code{\link[RISmed]{EUtilsSummary}} \code{\link[RISmed]{EUtilsGet}}
#' @examples
#' \dontrun{
#' library(RISmed)
#' res <- EUtilsSummary("myeloma[ti]",retmax=2,reldate=365)
#' fetch <- EUtilsGet(res)
#' format_RISmed(fetch)
#' }
format_RISmed <- function(x) {
    UseMethod("format_RISmed")
}

#' @export
format_RISmed.default <- function(x) {
    stop("x must be of class Medline")
}

#' @export
format_RISmed.Medline <- function(x) {

    auth <- auth_matrix(x)

    out <- data.frame("TITLE"= RISmed::ArticleTitle(x),
                      "ABSTRACT"= RISmed::AbstractText(x),
                      auth,
                      "SOURCE" = RISmed::Title(x),
                      "YEAR" = RISmed::YearPubmed(x),
                      "VOLUME" = RISmed::Volume(x),
                      "ISSUE" = RISmed::Issue(x),
                      "PAGES" = RISmed::MedlinePgn(x),
                      "DOI" = RISmed::ELocationID(x),
                      "DATABASE" = "PubMed",
                      stringsAsFactors = F)
    out[is.na(out)] <- ""
    return(add_pubname(out))
}


# -------------------------------------------------------------------------
# Helper functions to extract author names returned by the RISmed::Author()
# function
fl_auth <- function(x) {
    last_idx <- nrow(x)
    # Leaves last author last name and initials blank if there is only one
    # author
    if (last_idx > 1) {
        return(c(FIRSTAUTHLN = x[1, "LastName"],
                   FIRSTAUTHINIT = x[1, "Initials"],
                   LASTAUTHLN = x[last_idx, "LastName"],
                   LASTAUTHINIT = x[last_idx, "Initials"]))
    } else {
        return(c(FIRSTAUTHLN = x[1, "LastName"],
                 FIRSTAUTHINIT = x[1, "Initials"],
                 LASTAUTHLN = "",
                 LASTAUTHINIT = ""))
    }
}

auth_matrix <- function(x) {
    auth_list <- RISmed::Author(x)
    return(t(sapply(auth_list, fl_auth)))
}

# -------------------------------------------------------------------------
# To create a shorthand name for the publication based on first author name,
# initial, and year of publication
add_pubname <- function(x) {
    x[, "PUB"] <- paste0(x[, "FIRSTAUTHLN"],
                         " ",
                         x[, "FIRSTAUTHINIT"],
                         ", ",
                         x[, "YEAR"])
    return(x)
}